export const doctor_categories = [
  "IMMUNOLOGIST",
  "CARDIOLOGIST",
  "NEUROLOGIST",
  "DERMATOLOGIST",
  "ENT",
  "GASTROENTEROLOGIST",
  "GENERAL PHYSICIAN",
  "GYNAECOLOGIST",
  "INFECTIOUS DISEASE SPECIALIST",
  "NEPHROLOGIST",
  "ORTHOPAEDIC SURGEON",
  "PAEDIATRICIAN",
  "PSYCHIATRIST",
];

export const lab_tests = [
  "CBC",
  "ESR",
  "BLOOD SUGAR",
  "LIPID PROFILE",
  "LIVER FUNCTION TEST",
  "THYROID PROFILE",
  "URINE ROUTINE",
  "URINE MICROSCOPY",
  "X-RAY CHEST",
];
